name: Docker Image Dev
on:
  push:
    branches: 
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v1
    - name: Docker Login
      run: docker login -u germey -p {{ secrets.DOCKER_HUB_PASSOWRD }}
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
      with:
        version: 10.x
    - name: Build Frontend Source
      run: |
        echo "path"
        pwd
        ls
        cd gerapy/client
        npm install
        npm run build
    - name: Build the Docker Image
      run: |
        docker pull germey/docker:master
        docker build -t germey/docker:master ./docker/
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Push the Docker Image
        run: docker push germey/docker:master
