name: Sync Docs

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set SSH Environment
      run: |
        mkdir ~/.ssh
        chmod 700 ~/.ssh
        cd ~/.ssh
        echo "files in .ssh"
        ls
        ssh-keyscan github.com > ~/.ssh/known_hosts
        ssh-keyscan github.com > ~/.ssh/known_hosts
        echo "66666666666666666666666666666"
        cat ~/.ssh/known_hosts
        echo "xxxxxxxxxxx"
        curl https://raw.githubusercontent.com/Gerapy/Gerapy/master/deploy/key > ~/.ssh/subtree
        cd ~/.ssh
        cat ~/.ssh/subtree
        echo "ls"
        ls
        ssh-add ~/.ssh/subtree
        echo "77777777777"
        cat ~/.ssh/subtree
    - name: Sync With Docs
      run: |
        cd /tmp
        git clone git@github.com:Gerapy/Docs.git /tmp/Docs --bare
        cd /tmp/Docs
        ls
        cd /tmp
        git clone https://github.com/Gerapy/Gerapy.git
        cd Gerapy
        git subtree split --prefix=docs --squash -b docs
        git push /tmp/Docs docs:docs
        cd /tmp/Docs
        git checkout master
        git reset --hard docs
        git push origin master
        
        
        
