name: Sync Docs

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set SSH Environment
      run: |
        ssh-keygen -f id_rsa -t rsa -N ''
        echo "id_rsa"
        cat ~/.ssh/id_rsa.pub
        ssh-keyscan github.com > ~/.ssh/known_hosts
    - name: Sync With Docs
      run: |
        cd /tmp
        git clone git@github.com:Gerapy/Docs.git /tmp/Docs --bare
        cd /tmp/Docs
        ls
        cd /tmp
        git clone https://github.com/Gerapy/Gerapy.git
        cd Gerapy
        git subtree split --prefix=docs --squash -b docs
        git push /tmp/Docs docs:docs
        cd /tmp/Docs
        git checkout master
        git reset --hard docs
        git push origin master
        
        
        
