name: Sync Docs

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set SSH Environment
      run: |
        mkdir ~/.ssh
        chmod 700 ~/.ssh
        echo ${DEPLOY_DOCS_PRIVATE_KEY} > ~/.ssh/subtree
        ssh-keyscan github.com > ~/.ssh/known_hosts
        chmod 600 ~/.ssh/subtree
        ssh-add ~/.ssh/subtree
        echo "77777777777"
        cat ~/.ssh/subtree
    - name: Sync With Docs
      run: |
        cd /tmp
        git clone git@github.com:Gerapy/Docs.git /tmp/Docs --bare
        cd /tmp/Docs
        ls
        cd /tmp
        git clone https://github.com/Gerapy/Gerapy.git
        cd Gerapy
        git subtree split --prefix=docs --squash -b docs
        git push /tmp/Docs docs:docs
        cd /tmp/Docs
        git checkout master
        git reset --hard docs
        git push origin master
        
        
        
