name: Sync Docs

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Sync With Docs
      env: 
        DEPLOY_KEY: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC8wnqWGFGCTQJX2SQid0u+LYqVjWqw5B1Upibn2J5W8kC0WqD5Pcd3RcE/92L6PWDsDDnUFbqfHiAWWz1oziNo7yyJfvPNjWN7Q0jmyN/cErKdeWr3QeZYU65v1kr24M0ly8Rpgrm67d91mCF49oSo0w278ELY/1kgUngMlfQ1JDDwYO1bpNhhs82My/e2ejWVQQqLDaG601hTbs0eThcGjBKvdqnQ8M1D3eNV6wSPV0IDvvqZIu5Hii6bfM3e8xQtiYWAsdatDnTvhoFd6swoteqKblhSzGoupRcJL6pcba1A7A5Wu25MBAfZtGwGbnDgPt0lxQCKJMrv3TP15ASz CQC@PRCHAZ13685D.fareast.corp.microsoft.com"
      run: |
        ls
        pwd
        mkdir ~/.ssh
        pwd
        chmod 700 ~/.ssh
        ssh-keyscan github.com > ~/.ssh/known_hosts
        echo "66666666666666666666666666666"
        cat ~/.ssh/known_hosts
        echo "xxxxxxxxxxx"
        echo $DEPLOY_KEY >> ~/.ssh/subtree
        
        chmod 0600 ~/.ssh/subtree
        echo "77777777777"
        cat ~/.ssh/subtree
        cd /tmp
        git clone git@github.com:Gerapy/Docs.git /tmp/Docs --bare
        cd /tmp/Docs
        ls
        cd /tmp
        git clone https://github.com/Gerapy/Gerapy.git
        cd Gerapy
        git subtree split --prefix=docs --squash -b docs
        git push /tmp/Docs docs:docs
        cd /tmp/Docs
        git checkout master
        git reset --hard docs
        git push origin master
        
        
        
